export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_TOKEN_ID = 'SET_TOKEN_ID'
export const ON_LOGIN_ERROR = 'ON_LOGIN_ERROR'

export const SET_RENT_STATICSTICS = 'SET_RENT_STATICSTICS'
export const SET_DEVICE_STATICSTICS = 'SET_DEVICE_STATICSTICS'


export const SET_ROLE_LIST = 'SET_ROLE_LIST'
export const ADD_ROLE_LIST = 'ADD_ROLE_LIST'
export const SET_MENU_PERMISSION_LIST = 'SET_MENU_PERMISSION_LIST'

export const SET_STAFF_LIST = 'SET_STAFF_LIST'